package lab6_exercise1;

public enum RugbyPosition {
	LOOSEHEAD, HOOKER, TIGHTHEAD, NUMBER4LOCK, NUMBER5LOCK, BLINDSIDEFLANKER, 
	OPENSIDEFLANKER, NUMBER8, SCRUMHALF, FLYHALF, LEFTWING, INSIDECENTRE, OUTSIDECENTRE, RIGHTWING, FULLBACK;
	
	private RugbyPosition() {
	}
}
